### PR TITLE
add sidekiq and redis

### PR DESCRIPTION
**Pull request by grassiricardo**

### CODE REVIEW

**Comment by grassiricardo** [comment]
@luizkowalski What do you think about this implementation?

**Comment by luizkowalski** [comment]
LGTM, but we need to add a user/password to sidekiq, otherwise will be open to the world (see this https://stackoverflow.com/a/13409418/587406)

besides, I think you can increase the concurrency number (try with 5)

**Comment by grassiricardo** [comment]
@luizkowalski I am not able to use the secrets.yml credentials in my sidekiq.rb authentication. Any tips?

**Comment by luizkowalski** [comment]
use a environment variable then

**Pull request merged**
